import "./globals.css";

export const metadata = {
  title: "Poké API ",
  description: "Generated by create next app",
  icons: {
        icon: [
            {
                url: "/icons/favicon.ico",
                sizes: "any",
            }
        ],
        shortcut: "/icons/favicon.ico",
        apple: "/icons/favicon.ico",
    },
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        {children}
      </body>
    </html>
  );
}
